### ISSUE TITLE
Ubuntu Build Script Fails to Generate Passwords

### ISSUE THREAD

**Issue by ecapuano** [orlikoski/Skadi#89] opened 2019-01-02 02:48 UTC
At the tail end of the Ubuntu build script, it fails on the step where it attempts to randomly create the credentials. This is a brand new Ubuntu 16.04 system built only for this purpose.

```
Using random username and passwords for OS Account, TimeSketch, Nginx proxy, and Grafana
==> Creating skadi_HXYs user
BAD PASSWORD: it is too simplistic/systematic
BAD PASSWORD: it is too simplistic/systematic
BAD PASSWORD: it is too simplistic/systematic
chpasswd: (user skadi_HXYs) pam_chauthtok() failed, error:
Have exhausted maximum number of retries for service
chpasswd: (line 1, user skadi_HXYs) password not changed
```

**Comment by orlikoski** [comment] 2019-01-02 19:02
Interesting.  I'm most interested in why it failed and needed the `pip install setuptools`. Do you remember which command or what part of the output where it failed?

The rest of it has to do with the variables of the script not printing out at the end as you pointed out

**Comment by orlikoski** [comment] 2019-01-02 21:57
I think the issue is fixed with a small tweak to the installer. I think you were using the Desktop version and it was failing due to `git` not being installed by default in the Desktop version of Ubuntu. Try using the new installer (same installation instructions as before) and let me know what happens

**Comment by ecapuano** [comment] 2019-01-02 22:01
I was using server

**Comment by orlikoski** [comment] 2019-01-02 22:04
Well, if you were using server then let me know how the new installer works. It was tested and built on a 16.04.5 version of Ubuntu Server

**Comment by orlikoski** [comment] 2019-01-02 22:09
It might be there is a command character going into the username (like `:` or `/` or something)

**Comment by orlikoski** [comment] 2019-01-02 22:17
I think that the `git` and `setuptools` were red herrings. I think the issue is that some form of command / control characters were going into the username.

**Comment by orlikoski** [comment] 2019-01-02 22:44
The build script is updated and now the username is now fixed as `skadi`. It will make it with a random password generated at run time if the user doesn't already exist.

**Comment by orlikoski** [comment] 2019-01-02 22:45
I'm going to close this and I'll re-address if it comes back up. Thanks for letting me know about it

**Closed by orlikoski** 2019-01-02 22:45 UTC
Labels: bug, enhancement

**Comment by ecapuano** [comment] 2019-01-03 02:02
Thanks for consolidating a kick ass application stack!
